### ISSUE TITLE
Hosting issue

### ISSUE THREAD

**Issue by HariAakash646** [dmis-lab/covidAsk#7]
I had manually downloaded the packages but while hosting this issue seems to pop up:
`Traceback (most recent call last):
  File "C:\Users\HariAkash\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\HariAkash\AppData\Roaming\Python\Python38\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\HariAkash\AppData\Roaming\Python\Python38\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it:`

Any ideas on how to fix it?

Thanks.

**Comment by jhyuklee** [comment]
Hi, it seems that the machine you are trying to use to host the server has permission issue. Could you check it?

**Comment by HariAakash646** [comment]
So how do I check the permission issues... 
What permissions do I need to check exactly?

**Comment by jhyuklee** [comment]
Our code is based on a linux server so if you are using a Window server, you'll need to find out a way to figure out. Maybe this will help: https://stackoverflow.com/questions/12993276/errno-10061-no-connection-could-be-made-because-the-target-machine-actively-re

**Comment by HariAakash646** [comment]
> Our code is based on a linux server so if you are using a Window server, you'll need to find out a way to figure out. Maybe this will help: https://stackoverflow.com/questions/12993276/errno-10061-no-connection-could-be-made-because-the-target-machine-actively-re

I tried working it out on a linux machine... Almost everything works except for the final parts.... That is the results don't pop up and there is a "The server took too long to respond " Error after about 5 mins...
